import puppeteer from "puppeteer";
export declare const E2E_TIMEOUT: number;
export declare const timeout: (n: number) => Promise<unknown>;
export declare function setupPuppeteer(): {
    page: () => puppeteer.Page;
    click: (selector: string, options?: puppeteer.ClickOptions | undefined) => Promise<void>;
    count: (selector: string) => Promise<number>;
    text: (selector: string) => Promise<string | null>;
    value: (selector: string) => Promise<string>;
    html: (selector: string) => Promise<string>;
    classList: (selector: string) => Promise<any[]>;
    children: (selector: string) => Promise<any[]>;
    isVisible: (selector: string) => Promise<boolean>;
    isChecked: (selector: string) => Promise<boolean>;
    isFocused: (selector: string) => Promise<boolean>;
    setValue: (selector: string, value: string) => Promise<void>;
    typeValue: (selector: string, value: string) => Promise<void>;
    enterValue: (selector: string, value: string) => Promise<void>;
    clearValue: (selector: string) => Promise<string>;
    timeout: (time: number) => Promise<unknown>;
    nextFrame: () => Promise<unknown>;
};
